bookinfor/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index),

    path('ajax_get_phone_list/', views.ajax_get_phone_list),
    path('ajax_get_book_list/', views.ajax_get_book_list),

    path('book_query/', views.book_query),
    path('book_import/', views.book_import),

    path('member_query/', views.member_query),
    path('member_manage/', views.member_manage),
    path('member_new', views.member_new),
    path('member_modify/', views.member_modify),
    path('member_log/', views.member_log),

    path('deal_query/', views.deal_query),
    path('deal_manage/', views.deal_manage),
    path('deal_new', views.deal_new),

    path('inout_query/', views.inout_query),
    path('inout_manage/', views.inout_manage),
    path('inout_out_new', views.inout_out_new),
    path('inout_in_new', views.inout_in_new),
    path('inout_modify/', views.inout_modify),
    path('inout_log/', views.inout_log),
]

tushu/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.routers import DefaultRouter
from bookinfor.views import AuthorViewSet, SortViewSet, PublishViewSet, BookinforViewSet, BookmemberViewSet, ConsumeViewSet, InoutrecordViewSet


router = DefaultRouter()
router.register(r'author', AuthorViewSet)
router.register(r'sort', SortViewSet)
router.register(r'publish', PublishViewSet)
router.register(r'bookinfor', BookinforViewSet)
router.register(r'bookmember', BookmemberViewSet)
router.register(r'consume', ConsumeViewSet)
router.register(r'inoutrecord', InoutrecordViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='admin/login.html')),
    path('accounts/logout/', auth_views.LogoutView.as_view()),
    path('', include('bookinfor.urls')),

    # drf 自动注册路由
    path('api/', include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookinfor/models.py
from django.db import models
import time

class Author(models.Model):
  chn_name = models.CharField(max_length=20, null=True, blank=True, verbose_name='中文名称')
  for_name = models.CharField(max_length=20, null=True, blank=True, verbose_name='外文名称')
  area = models.CharField(max_length=20, null=True, blank=True, verbose_name='国家/地区')
  birth = models.CharField(max_length=20, null=True, blank=True, verbose_name='出生年月')
  remark = models.CharField(max_length=100, null=True, blank=True, verbose_name='备注')


  def __str__(self):
    return self.chn_name


class Bookseries(models.Model):
  name = models.CharField(max_length=50, verbose_name='系列名称')

  def __str__(self):
    return self.name


class Sort(models.Model):
  name = models.CharField(max_length=50, verbose_name='类别')

  def __str__(self):
    return self.name


class Publish(models.Model):
  name = models.CharField(max_length=50, verbose_name='出版社')

  def __str__(self):
    return self.name


class Bookinfor(models.Model):
  sn = models.CharField(max_length=20, primary_key=True, verbose_name='SN')
  book_name = models.CharField(max_length=30, verbose_name='书名')
  book_set_name = models.CharField(max_length=20, null=True, blank=True, verbose_name='套装名称')
  series_name = models.ForeignKey(Bookseries, on_delete=models.CASCADE, null=True, blank=True, verbose_name='系列名称')
  publisher = models.ForeignKey(Publish, on_delete=models.CASCADE, null=True, blank=True, verbose_name='出版社')
  size = models.CharField(max_length=20, null=True, blank=True, verbose_name='大小')

  edition = models.CharField(max_length=30, null=True, blank=True, verbose_name='版次')
  price = models.CharField(max_length=10, null=True, blank=True, verbose_name='定价')
  author_text = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True, related_name='author_text', verbose_name='著')
  author_picture = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True, related_name='author_picture', verbose_name='绘')
  translation = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True, related_name='translation', verbose_name='翻译')

  setset = models.CharField(max_length=10, null=True, blank=True, verbose_name='套装', choices=(('s','是'),('f','否')))
  hardcover = models.CharField(max_length=10, null=True, blank=True, verbose_name='装订', choices=(('jingz','精装'),('jianz','简装')))
  sortname = models.ForeignKey(Sort, on_delete=models.CASCADE, null=True, blank=True, verbose_name='类别')
  pinyin = models.CharField(max_length=10, null=True, blank=True, verbose_name='拼音')
  per_amount = models.CharField(max_length=20, null=True, blank=True, verbose_name='每套几本')
  book_status = models.CharField(max_length=10, null=True, blank=True, verbose_name='状态', default='未借出')
  book_paper = models.CharField(max_length=10, null=True, blank=True, verbose_name='纸张')

  position = models.CharField(max_length=20, null=True, blank=True, verbose_name='存放位置')
  language = models.CharField(max_length=20, null=True, blank=True, verbose_name='语言')
  true_price = models.CharField(max_length=20, null=True, blank=True, verbose_name='购买价格')
  book_link = models.CharField(max_length=50, null=True, blank=True, verbose_name='链接')
  isbn = models.CharField(max_length=20, null=True, blank=True, verbose_name='ISBN')
  remark1 = models.CharField(max_length=20, null=True, blank=True, verbose_name='备注1')

  def __str__(self):
    return '%s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s %s' % (self.sn, self.book_name, self.book_set_name, self.series_name, self.publisher, self.size, self.edition, self.price, self.author_text, self.author_picture, self.translation, self.setset, self.hardcover, self.sortname, self.pinyin, self.per_amount, self.book_status, self.book_paper, self.position, self.language, self.true_price, self.book_link, self.isbn, self.remark1)



class Bookmember(models.Model):
  phone = models.CharField(primary_key=True, max_length=20, verbose_name='电话')
  name = models.CharField(max_length=20, null=True, blank=True, verbose_name='姓名')
  account = models.CharField(max_length=20, null=True, blank=True, verbose_name='社交帐号')
  mail = models.CharField(max_length=20, null=True, blank=True, verbose_name='邮箱')
  begin = models.DateTimeField(null=True, blank=True, verbose_name='注册时间', auto_now_add = True)
  expir = models.DateTimeField(null=True, blank=True, verbose_name='过期时间', auto_now = False)
  deposit = models.IntegerField(null=True, blank=True, verbose_name='押金', default="0")
  remain = models.IntegerField(null=True, blank=True, verbose_name='剩余金额', default="0")
  handler = models.CharField(max_length=10, null=True, blank=True, verbose_name='创建人')
  remark = models.CharField(max_length=100, null=True, blank=True, verbose_name='备注')


  def __str__(self):
    return self.phone
#    return '%s %s' % (self.phone, self.remain)



class Consume(models.Model):
  phone = models.CharField(max_length=20, verbose_name='电话')
  consumetime = models.DateTimeField(null=True, blank=True, verbose_name='消费时间', auto_now_add = True)
  money = models.CharField(max_length=20, null=True, blank=True, verbose_name='消费金额')
  handler = models.CharField(max_length=20, null=True, blank=True, verbose_name='操作人')
  sort = models.CharField(max_length=20, null=True, blank=True, verbose_name='类型', choices=(('cz','充值'),('xf','消费')))
  over = models.CharField(max_length=20, null=True, blank=True, verbose_name='余额')
  remark = models.CharField(max_length=100, null=True, blank=True, verbose_name='备注')


  def __str__(self):
    return self.phone



class Inoutrecord(models.Model):
  inoutnumber = models.CharField(max_length=20, verbose_name='单号')
  phone = models.CharField(max_length=20, verbose_name='电话')
  outtime = models.DateTimeField(null=True, blank=True, verbose_name='借出时间', auto_now_add = True)
  intime = models.DateTimeField(null=True, blank=True, verbose_name='归还时间')
  name = models.CharField(max_length=20, null=True, blank=True, verbose_name='书名')
  sn = models.CharField(max_length=20, null=True, blank=True, verbose_name='SN')
  handlerout = models.CharField(max_length=20, null=True, blank=True, verbose_name='操作人出')
  handlerin = models.CharField(max_length=20, null=True, blank=True, verbose_name='操作人还')
  remark = models.CharField(max_length=100, null=True, blank=True, verbose_name='备注')


  def __str__(self):
    return self.phone

templates/bookinfor/bookinfor/book_import.html
{% extends 'base.html' %}
{% block book_import_block %}<li class="active">{% endblock %}
{% block head_block %}Book Import{% endblock %}

{% block body_block %}

<form class="form-horizontal" role="form" action="" method="post">

  {% csrf_token %}

  <div class="form-group">
      <label for="booklink" class="col-sm-2 control-label">链接</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="booklink" value="{{ booklink }}" placeholder="请输入书的链接地址">
      </div>
   </div>

  <div class="form-group">
      <label for="bookname" class="col-sm-2 control-label">书名</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="bookname" value="{{ bookname }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="author" class="col-sm-2 control-label">作者</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="author" value="{{ author }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="publisher" class="col-sm-2 control-label">出版社</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="publisher" value="{{ publisher }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="edition" class="col-sm-2 control-label">出版时间</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="edition" value="{{ edition | cut:'出版时间:' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="price" class="col-sm-2 control-label">定价</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="price" value="{{ price }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="size" class="col-sm-2 control-label">大小</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="size" value="{{ size | cut:'</li>'| cut:'开 本：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="paper" class="col-sm-2 control-label">纸张</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="paper" value="{{ paper | cut:'</li>'| cut:'纸 张：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="hardcover" class="col-sm-2 control-label">包装</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="hardcover" value="{{ hardcover | cut:'</li>' | cut:'包 装：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="setset" class="col-sm-2 control-label">套装</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="setset" value="{{ setset | cut:'</li>'|cut:'是否套装：' }}" readonly="readonly">
      </div>
   </div>

   <hr class="hr" />

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
      <input id="querydata" name="cx" type="submit" class="btn btn-default" value="查询" data-loading-text="查询中......">
      <input id="importdata" name="importdata" type="submit" class="btn btn-default" value="提交" data-loading-text="提交中......">
    </div>
  </div>

</form>



{% endblock %}

templates/bookinfor/bookinfor/book_import_link_error.html
{% extends 'base.html' %}
{% block book_import_block %}<li class="active">{% endblock %}
{% block head_block %}Book Link Error, Please Check!!! {% endblock %}

{% block body_block %}

<form class="form-horizontal" role="form" action="" method="post">

  {% csrf_token %}

  <div class="form-group">
      <label for="booklink" class="col-sm-2 control-label">链接</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="booklink" value="{{ booklink }}" placeholder="请输入书的链接地址">
      </div>
   </div>

  <div class="form-group">
      <label for="bookname" class="col-sm-2 control-label">书名</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="bookname" value="{{ bookname }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="author" class="col-sm-2 control-label">作者</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="author" value="{{ author }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="publisher" class="col-sm-2 control-label">出版社</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="publisher" value="{{ publisher }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="edition" class="col-sm-2 control-label">出版时间</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="edition" value="{{ edition | cut:'出版时间:' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="price" class="col-sm-2 control-label">定价</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="price" value="{{ price }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="size" class="col-sm-2 control-label">大小</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="size" value="{{ size | cut:'</li>'| cut:'开 本：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="paper" class="col-sm-2 control-label">纸张</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="paper" value="{{ paper | cut:'</li>'| cut:'纸 张：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="hardcover" class="col-sm-2 control-label">包装</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="hardcover" value="{{ hardcover | cut:'</li>' | cut:'包 装：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="setset" class="col-sm-2 control-label">套装</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="setset" value="{{ setset | cut:'</li>'|cut:'是否套装：' }}" readonly="readonly">
      </div>
   </div>

   <hr class="hr" />

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
      <input id="querydata" name="cx" type="submit" class="btn btn-default" value="查询" data-loading-text="查询中......">
      <input id="importdata" name="importdata" type="submit" class="btn btn-default" value="提交" data-loading-text="提交中......">
    </div>
  </div>

</form>



{% endblock %}

templates/bookinfor/bookinfor/book_import_ok.html
{% extends 'base.html' %}
{% block book_import_block %}<li class="active">{% endblock %}
{% block head_block %}Book Import OK!!!{% endblock %}

{% block body_block %}

<form class="form-horizontal" role="form" action="" method="post">

  {% csrf_token %}

  <div class="form-group">
      <label for="booklink" class="col-sm-2 control-label">链接</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="booklink" value="{{ booklink }}" placeholder="请输入书的链接地址">
      </div>
   </div>

  <div class="form-group">
      <label for="bookname" class="col-sm-2 control-label">书名</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="bookname" value="{{ bookname }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="author" class="col-sm-2 control-label">作者</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="author" value="{{ author }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="publisher" class="col-sm-2 control-label">出版社</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="publisher" value="{{ publisher }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="edition" class="col-sm-2 control-label">出版时间</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="edition" value="{{ edition | cut:'出版时间:' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="price" class="col-sm-2 control-label">定价</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="price" value="{{ price }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="size" class="col-sm-2 control-label">大小</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="size" value="{{ size | cut:'</li>'| cut:'开 本：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="paper" class="col-sm-2 control-label">纸张</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="paper" value="{{ paper | cut:'</li>'| cut:'纸 张：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="hardcover" class="col-sm-2 control-label">包装</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="hardcover" value="{{ hardcover | cut:'</li>' | cut:'包 装：' }}" readonly="readonly">
      </div>
   </div>

   <div class="form-group">
      <label for="setset" class="col-sm-2 control-label">套装</label>
      <div class="col-sm-3">
         <input type="text" class="form-control" name="setset" value="{{ setset | cut:'</li>'|cut:'是否套装：' }}" readonly="readonly">
      </div>
   </div>

   <hr class="hr" />

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-3">
      <input id="querydata" name="cx" type="submit" class="btn btn-default" value="查询" data-loading-text="查询中......">
      <input id="importdata" name="importdata" type="submit" class="btn btn-default" value="提交" data-loading-text="提交中......" style="VISIBILITY: hidden">
    </div>
  </div>

</form>



{% endblock %}

templates/bookinfor/bookinfor/book_query.html
{% extends 'base.html' %}
{% block book_query_block %}<li class="active">{% endblock %}
{% block head_block %}Book Query{% endblock %}

{% block body_block %}

<form action="" method="get">

  <div class="form-group">
      <div class="col-sm-3">
         <input type="text" class="form-control" name="bookname" placeholder="请输入要搜索的书名">
      </div>
   </div>


  <div class="btn-group">
    <input type="submit" class="btn btn-default" name="querydata" value="搜索"></input>
  </div>


<hr class="hr" />

<div class="table-responsive">
  <table class="table table-condensed table-striped table-hover">
    
    <thead>
    <tr>
      <th>序号</th>
      <th>SN</th>
      <th>书名</th>
      <th>套装名称</th>
      <th>系列名称</th>
      <th>出版社</th>
      <th>大小</th>
      <th>版次</th>
      <th>定价</th>
      <th>著</th>
      <th>绘</th>
      <th>翻译</th>
      <th>套装</th>
      <th>装订</th>
      <th>类别</th>
      <th>拼音</th>
      <th>每套几本</th>
      <th>状态</th>
      <th>纸张</th>
      <th>存放位置</th>
      <th>语言</th>
      <th>购买价格</th>
      <th>链接</th>
      <th>ISBN</th>
      <th>备注1</th>
    </tr>
    </thead>

    <tbody>
    <tr>
      {% for bookinfor in bookinfor %}
      <tr class="info">
        <td>{{ forloop.counter }}</td>
        <td>{{ bookinfor.sn }}</td>
        <td>{{ bookinfor.book_name }}</td>
        <td>{{ bookinfor.book_set_name }}</td>
        <td>{{ bookinfor.series_name }}</td>
        <td>{{ bookinfor.publisher }}</td>
        <td>{{ bookinfor.size }}</td>
        <td>{{ bookinfor.edition }}</td>
        <td>{{ bookinfor.price }}</td>
        <td>{{ bookinfor.author_text}}</td>
        <td>{{ bookinfor.author_picture }}</td>
        <td>{{ bookinfor.translation }}</td>
        <td>{{ bookinfor.get_setset_display }}</td>
        <td>{{ bookinfor.get_hardcover_display }}</td>
        <td>{{ bookinfor.sortname }}</td>
        <td>{{ bookinfor.pinyin }}</td>
        <td>{{ bookinfor.per_amount }}</td>
        <td>{{ bookinfor.book_status }}</td>
        <td>{{ bookinfor.book_paper }}</td>
        <td>{{ bookinfor.position }}</td>
        <td>{{ bookinfor.language }}</td>
        <td>{{ bookinfor.true_price }}</td>
        <td>{{ bookinfor.book_link }}</td>
        <td>{{ bookinfor.isbn }}</td>
        <td>{{ bookinfor.remark1 }}</td>


      </tr>
      {% endfor %}
    </tr>
    </tbody>

  </table>
</div>

{% endblock %}